### ISSUE TITLE
error while loading shared libraries: libQt5Widgets.so.5

### ISSUE THREAD

**Issue by villares** [xxyxyz/even#2]
Thanks for Flat and for this!

I'm on Ubuntu 20.04 and I have installed Qt5 and PyPy, I'm getting this as I try to execute Even:
`even-0.2-linux/Even: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory`

Please advise if I'm doing something wrong or if you'd like more information to reproduce. I understand if this will no longer be maintained and if I get no answer. Cheers!

**Comment by sukop** [comment]
Could you please try `sudo apt-get install qt5-default:i386`? I then still got some font errors but I tried it on Xubuntu 20.04 so you might end up more lucky. In any case, let me know if it got you somewhere.

**Comment by villares** [comment]
A window opens, but no text is white/invisible. Thank you!

```
drawing failure for widget 'GtkFileChooserDialog': error occurred in libfreetype
render glyph failed err=13 face=0xa351370, glyph=39
render glyph failed err=13 face=0xa351370, glyph=82
render glyph failed err=13 face=0xa351370, glyph=3
render glyph failed err=13 face=0xa351370, glyph=92
render glyph failed err=13 face=0xa351370, glyph=82
render glyph failed err=13 face=0xa351370, glyph=88
render glyph failed err=13 face=0xa351370, glyph=3
render glyph failed err=13 face=0xa351370, glyph=90
render glyph failed err=13 face=0xa351370, glyph=68
render glyph failed err=13 face=0xa351370, glyph=81
render glyph failed err=13 face=0xa351370, glyph=82
render glyph failed err=13 face=0xa351370, glyph=3
render glyph failed err=13 face=0xa351370, glyph=86
render glyph failed err=13 face=0xa351370, glyph=89
render glyph failed err=13 face=0xa351370, glyph=87
render glyph failed err=13 face=0xa351370, glyph=75
render glyph failed err=13 face=0xa351370, glyph=68
render glyph failed err=13 face=0xa351370, glyph=81
render glyph failed err=13 face=0xa351370, glyph=74
render glyph failed err=13 face=0xa351370, glyph=72
render glyph failed err=13 face=0xa351370, glyph=86
render glyph failed err=13 face=0xa351370, glyph=80
render glyph failed err=13 face=0xa351370, glyph=68
render glyph failed err=13 face=0xa351370, glyph=71
render glyph failed err=13 face=0xa351370, glyph=75
render glyph failed err=13 face=0xa351370, glyph=72
render glyph failed err=13 face=0xa351370, glyph=3
render glyph failed err=13 face=0xa351370, glyph=70
render glyph failed err=13 face=0xa351370, glyph=88
render glyph failed err=13 face=0xa351370, glyph=80
render glyph failed err=13 face=0xa351370, glyph=521
render glyph failed err=13 face=0xa351370, glyph=56
render glyph failed err=13 face=0xa351370, glyph=79
render glyph failed err=13 face=0xa351370, glyph=71
render glyph failed err=13 face=0xa351370, glyph=522
render glyph failed err=13 face=0xa351370, glyph=34
render glyph failed err=13 face=0xa351370, glyph=54
render glyph failed err=13 face=0xa351370, glyph=68
render glyph failed err=13 face=0xa351370, glyph=89
render glyph failed err=13 face=0xa351370, glyph=38
render glyph failed err=13 face=0xa351370, glyph=81
render glyph failed err=13 face=0xa351370, glyph=79
render glyph failed err=13 face=0xa351370, glyph=82
render glyph failed err=13 face=0xa351370, glyph=86
render glyph failed err=13 face=0xa351370, glyph=88
render glyph failed err=13 face=0xa351370, glyph=87
render glyph failed err=13 face=0xa351370, glyph=76
render glyph failed err=13 face=0xa351370, glyph=60
render glyph failed err=13 face=0xa351370, glyph=85
render glyph failed err=13 face=0xa351370, glyph=70
render glyph failed err=13 face=0xa351370, glyph=75
render glyph failed err=13 face=0xa351370, glyph=81
render glyph failed err=13 face=0xa351370, glyph=74
render glyph failed err=13 face=0xa351370, glyph=86
render glyph failed err=13 face=0xa351370, glyph=90
render glyph failed err=13 face=0xa351370, glyph=79
render glyph failed err=13 face=0xa351370, glyph=69
render glyph failed err=13 face=0xa351370, glyph=73
render glyph failed err=13 face=0xa351370, glyph=518
render glyph failed err=13 face=0xa351370, glyph=89
render glyph failed err=13 face=0xa351370, glyph=80
render glyph failed err=13 face=0xa351370, glyph=17
```

![image](https://user-images.githubusercontent.com/3694604/91627107-568c9080-e98b-11ea-919b-8f873a1041dd.png)

**Comment by sukop** [comment]
Yep, those were the errors I got as well...

It's an error from FreeType which Even doesn't directly use so maybe something between Qt versions changed, I'm not sure. I also tried to recompile the project with `apt-get install qtcreator` on newer Xubuntu but that didn't work either. What did work (for me) was installing Qt Creator from 5.9.x Offline Installer directly from qt.io and rebuilding the project as it is here on GitHub. If you want, I have a 27MB compressed binary which I can try to attach here or you could try to recompile it yourself. You also might want to replace the bundled Flat in `even/thirdparty/lib/flat` with the most recent version but keep in mind the version of PyPy you installed via `apt-get install pypy` (since version 0.3, Flat supports only Python 3).

**Comment by villares** [comment]
Thank you for your kind attention. I think I won't have the necessary skills to recompile it and nor the time to struggle with the instructions (and that might consume precious time from you to instruct me too...). For the time being I'm going to try and use flat by itself! <3

**Comment by sukop** [comment]
Ok, so closing for now, when a new release eventually comes it should (I hope!) be fixed by virtue of using newer setup.

**Comment by sukop** [comment]
I've just pushed a new release which hopefully fixes the above issue.
